name: Documentation
description: Update or add documentation
title: "[DOCS]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this out!
  - type: textarea
    id: describe-need
    attributes:
      label: Describe the need
      description: What do you wish was different about our docs?
      placeholder: Describe the need for documentation updates here.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../docs/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true