name: 🦄 Feature Request
description: Suggest an idea for a new feature or enhancement
title: "[FEAT]: "
labels: ["feature"]
assignees: ["techmely"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to complete this feature!
        Please carefully read the contribution guidelines before request a review from others.
        https://github.com/techmely/essential-packages/blob/main/docs/contribution.md#create-feature-request
  - type: textarea
    id: describe-feature
    attributes:
      label: What does this MR do and why?
      description: What do you want to happen? What problem are you trying to solve?
      placeholder: Describe the need for the feature.
    validations:
      required: true
  - type: textarea
    id: resources
    attributes:
      label: The resources that you have researched
      description: To solve this problem, what's resources we need to access?

  - type: checkboxes
    id: Acceptance-Criteria
    attributes:
      label: Acceptance Criteria Checklist
      description: The standard criteria that a feature must satisfy to be accepted
      options:
        - label: Read the [contribution guide](https://github.com/techmely/essential-packages/blob/main/docs/contribution.md)
        - label: Check existing [discussions](https://github.com/techmely/essential-packages/discussions) and [issues](https://github.com/techmely/essential-packages/issues).
          required: true
        - label: The scope of the feature is clear and small enough to be implemented in a single MR - Not exceeding 500 lines of code and 40 files changed.
          required: true
        - label: The time doing this feature does not exceed 1 day.
          required: true
